name: "Build with Docker"
description: "Build Docker image with specified name and tag."
inputs:
  path_dockerfile:
    description: "Path to Dockerfile"
    required: true
    default: 'Dockerfile'
  image_name:
    description: "Docker image name"
    required: true
  tag_name:
    description: "Docker image tag"
    required: false

runs:
  using: composite
  steps:
    - name: Set Dockerfile Path 
      shell: bash
      run: | 
        if [ -z "${{ inputs.path_dockerfile }}" ]; then
          echo "PATH_DOCKERFILE=src/main/docker/Dockerfile.jvm" >> $GITHUB_ENV
        else 
          echo "PATH_DOCKERFILE={{ inputs.path_dockerfile }} >> $GITHUB_ENV"
    - name: Set Docker Image Name 
      shell: bash
      run: | 
        if [ -z "${{ inputs.image_name }}" ]; then
          echo "IMAGE_NAME=academy" >> $GITHUB_ENV
        else 
          echo "IMAGE_NAME={{ inputs.image_name }}"  >> $GITHUB_ENV
    - name: Set Docker Tag
      shell: bash
      run: |
        # If tag_name is not provided, use Unix timestamp
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%d-%m-%y)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi

    - name: Build Docker Image
      shell: bash
      run: |
        docker build . --file "${{ env.PATH_DOCKERFILE }}" --tag "${{ env.IMAGE_NAME }}:${{env.TAG}}"
        # Export the full image name with tag to DOCKER_IMAGE_NAME
        echo "DOCKER_IMAGE_NAME=${{ env.IMAGE_NAME }}:${{env.TAG}}" >> $GITHUB_ENV

    - name: List Docker Image
      shell: bash
      run: docker image ls | grep "${{ env.IMAGE_NAME }}:${{env.TAG}}" | head -1
