name: "Build with Docker"
description: "Building with Docker"
runs:
  using: composite
  steps:
    - name: List docker image 
      shell: bash
      run: docker image ls | grep $(date +%d-%m-%y) | head -1