name: "Build with Docker"
description: "Building with Docker"
runs:
  using: composite
  steps:
  - name: Build Dockerfile
    shell: bash
    run: docker build . --file src/main/docker/Dockerfile.jvm --tag academy:$(date +%d-%m-%y)
  - name: List docker image 
    shell: bash
    run: docker image ls | grep $(date +%d-%m-%y) | head -1