name: "Build with Docker"
description: "Build Docker image with specified name and tag."
inputs:
  path_dockerfile:
    description: "Path to Dockerfile"
    required: true
    default: 'Dockerfile'
  image_name:
    description: "Docker image name"
    required: true
  tag_name:
    description: "Docker image tag"
    required: false

runs:
  using: composite
  steps:
    - name: Set Docker Tag
      shell: bash
      run: |
        # If tag_name is not provided, use Unix timestamp
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi

    - name: Build Docker Image
      shell: bash
      run: |
        docker build . --file "${{ inputs.path_dockerfile }}" --tag "${{ inputs.image_name }}:$TAG"
        # Export the full image name with tag to DOCKER_IMAGE_NAME
        echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}:$TAG" >> $GITHUB_ENV

    - name: List Docker Image
      shell: bash
      run: docker image ls | grep "${{ inputs.image_name }}:$TAG" | head -1
