name: "Docker Image Push"
description: "Pushes the docker image to Docker Hub"
inputs:
  docker_username:
    description: "Docker username"
    required: true
  docker_password:
    description: "Docker password"
    required: true
  image_name:
    description: "Full name of the Docker image (with tag)"
    required: true

runs:
  using: composite
  steps:
    - name: Tag Docker Image
      shell: bash
      run: |
        docker tag ${{inputs.image_name}} ${{ inputs.docker_username }}/${{inputs.image_name}}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ inputs.docker_username }}
          password: ${{ inputs.docker_password }}
    - name: Push Docker Image
      shell: bash
      run: |
        # Push the tagged image to Docker Hub
        docker push ${{ inputs.docker_username }}/${{inputs.image_name}}
