name: Docker Image Push
description: Push Docker image to Docker Hub
inputs:
  docker_username:
    description: "Docker username"
    required: true
  docker_token:
    description: "Docker token"
    required: true
  image_name:
    description: "Image name generated"
    required: true

runs:
  using: composite
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}
    - name: Tag Docker Image
      run: |
        echo ${{ inputs.image_name }}
        echo ${{ inputs.docker_username }}/${{ inputs.image_name }}
        docker tag ${{ inputs.image_name }} ${{ inputs.docker_username }}/${{ inputs.image_name }}
      shell: bash
    - name: Push Docker Image
      run: docker push ${{ inputs.docker_username }}/${{ inputs.image_name }}
      shell: bash